### ISSUE TITLE
Stack exhausted while compiling polymorph.

### ISSUE THREAD

**Issue by shamazmazum** [digikar99/polymorphic-functions#6]
Hi! Consider the following code:

~~~~
(defpackage compilation-failure
  (:use #:cl #:polymorphic-functions))
(in-package :compilation-failure)

(eval-when (:compile-toplevel :load-toplevel :execute)
  (push
   (lambda (s)
     (let* ((name (symbol-name s))
            (len  (length name)))
       (and (char= #\< (elt name 0))
            (char= #\> (elt name (1- len))))))
   *parametric-type-symbol-predicates*))

(defpolymorph failed-polymorph ((x <t>))
    (function (<t>) (values <t> &optional))
  (lambda (x)
    (1+ x)))
~~~~

If you try to compile it in SBCL 2.1.11, you will get the following:

~~~~
* (asdf:load-system :polymorphic-functions)
WARNING: System definition file #P"/home/vasily/.quicklisp/dists/ultralisp/software/AccelerationNet-collectors-20190319083844/collectors.asd" contains definition for system "collectors-test". Please only define "collectors" and secondary systems with a name starting with "collectors/" (e.g. "collectors/test") in that file.
WARNING: System definition file #P"/home/vasily/.quicklisp/dists/ultralisp/software/AccelerationNet-symbol-munger-20190319053317/symbol-munger.asd" contains definition for system "symbol-munger-test". Please only define "symbol-munger" and secondary systems with a name starting with "symbol-munger/" (e.g. "symbol-munger/test") in that file.
T
* (compile-file "~/test.lisp")
; compiling file "~/test.lisp" (written 30 DEC 2021 08:46:45 PM):
; processing (DEFPACKAGE COMPILATION-FAILURE ...)
; processing (IN-PACKAGE :COMPILATION-FAILURE)
; processing (EVAL-WHEN (:COMPILE-TOPLEVEL :LOAD-TOPLEVEL ...) ...)
; processing (DEFPOLYMORPH FAILED-POLYMORPH ...)INFO: Control stack guard page reprotected
INFO: Control stack guard page unprotected
Control stack guard page temporarily disabled: proceed with caution

debugger invoked on a SB-KERNEL::CONTROL-STACK-EXHAUSTED in thread
#<THREAD "main thread" RUNNING {1004E70183}>:
  Control stack exhausted (no more space for function call frames).
This is probably due to heavily nested or infinitely recursive function
calls, or a tail call that SBCL cannot or has not optimized away.

PROCEED WITH CAUTION.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

(SB-KERNEL::CONTROL-STACK-EXHAUSTED-ERROR)
0]
~~~~

Any idea how to fix it? Currently I replace return type with `function` and it suits my purpose, but I decided to report.

**Comment by digikar99** [comment]
This was indeed a bug in polymorphic-functions, thanks for reporting!

---

But I'd definitely discourage the use of parametric-types beyond trivial cases like `(array <t>)`. One factor is [CLHS entry for `CL:TYPEP`](http://clhs.lisp.se/Body/f_typep.htm) prohibits the use of `function` and `values` type-specifiers in their list forms. Similarly, for `CL:SUBTYPEP`, while I was unable to locate the relevant description in CLHS, both SBCL and CCL signal a "<...> type illlegal in this context" error for `values` type.

Further, in the particular example you shared, the issue of types is also the following:

```lisp
CL-USER> (type-of 1)
BIT
CL-USER> (type-of 2)
(INTEGER 0 4611686018427387903)
CL-USER> (type-of 3)
(INTEGER 0 4611686018427387903)
CL-USER> (type-of -1)
FIXNUM
CL-USER> (type-of 4611686018427387904)
(INTEGER 4611686018427387904)
```

And

```lisp
;;; on SBCL
(defpolymorph pp ((x <t>)) t
  <t>)
(pp 1) ;=> BIT
(pp 2) ;=> (INTEGER 0 4611686018427387903)
```

A workaround could be to first implement a `better-number` as an extended type that behaves more in accordance with intuitive expectations or the problem at hand, and then parameterize over this. 

Amidst this, [COALTON](https://github.com/coalton-lang/coalton/) might be a better tool for serious parametric-polymorphism.

**Comment by digikar99** [comment]
A sketch of what to do once `better-number` is available as an extended type (aka ctype, see subtypep, type=, supertypep in [src/extended-types](https://github.com/digikar99/polymorphic-functions/tree/master/src/extended-types)) is as follows:

```lisp
(defmethod parametric-type-run-time-lambda-body
    ((type-car (eql 'better-number)) type-cdr parameter)
  `(lambda (number)
     (etypecase number
       (fixnum 'fixnum)
       (single-float 'single-float)
       (double-float 'double-float))))

(defmethod parametric-type-compile-time-lambda-body
    ((type-car (eql 'better-number)) type-cdr parameter)
  `(lambda (number-type)
     (eswitch (number-type :test #'subtypep)
       ('fixnum 'fixnum)
       ('single-float 'single-float)
       ('double-float 'double-float))))

;;; Expected usage:
(defpolymorph pp ((x (better-number <t>))) t
  <t>)
(pp 1) ;=> fixnum
(pp -1) ;=> fixnum
(pp 1.0f0) ;=> single-float
(pp 1.0d0) ;=> double-float
```

**Comment by shamazmazum** [comment]
Thanks! Is TYPEP called every time on returned value (even if polymorph is statically dispatched)?

I use something like this in [imago](https://github.com/tokenrove/imago) library. The point is in generating good specialized code in compile time. `<t>` is used inside `cubic-interpolator` to create a small array with elements of type `<t>`. I see a good improvement in speed because there is no need in `array-element-type` and `aref` is open-coded.
~~~~
(defpolymorph cubic-interpolator ((pixels (array <t>))
                                  (constructor function)
                                  (accessors list))
    function
  ....)
~~~~

**Comment by digikar99** [comment]
There actually are three dispatch modes: dynamic, static-without-inlining, and static-with-inlining. The last case does indeed avoid TYPEP, while the first two rely on TYPEP. 

---

And, [I](https://github.com/tokenrove/imago/commit/60e91b6f208b985e04345adf278b315cb4f95dec#diff-cf8bf822cc3adafedb75c2acddf18a72b379e85e497209484e0469cbfd034713R47-L76) [see](https://github.com/tokenrove/imago/commit/60e91b6f208b985e04345adf278b315cb4f95dec#diff-cf8bf822cc3adafedb75c2acddf18a72b379e85e497209484e0469cbfd034713R150).

As far as optimization is concerned, in theory, you should get all the benefits of parametric-polymorphism using subtype polymorphism. The following produces the same assembly as the [example in the README](https://github.com/digikar99/polymorphic-functions/#could-you-elaborate-on-parametric-polymorphism).

```lisp
(defpolymorph my-aref ((x array)) t
  (cl:aref x 0))
(disassemble (lambda (a)
               (declare (optimize speed)
                        (type (simple-array single-float 1) a))
               (my-aref a)))
```

But that is in theory. OTOH, the first use case (the link at 'I' above) is actually a good one where in-practice, parametric-polymorphism could be more suited than subtype polymorphism. Inferring the return-type of `(apply constructor (mapcar ...))` could indeed be difficult for SBCL, let alone cl-form-types! Interesting use case!

In the second one (link at 'see'), once it is known at compile time that the type of `image-pixels` is `(array single-float)` and not just `array`, it is possible to infer that the return-value of `(array-element-type image-pixel)` is of type `(eql 'single-float)` at compile-time itself. And optimization can proceed as expected. Here, it does seem that subtype polymorphism is indeed sufficient, and parametric-polymorphism might not be needed just here. But again, as in the first use, parametric-polymorphism does help with specifying the return-type of `(apply constructor (mapcar ...))`.

Thanks for these use cases! They indeed do provide more motivation for continuing to fix and develop parametric-polymorphism :).
