### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [digikar99/polymorphic-functions#9]
Building with SBCL 2.2.7.28-02bc916fd / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 537d9e7dfffddd0b0d779b4ea01af4cab4583de3

*polymorphic-functions* fails to build with the following error:

```
; caught WARNING:
;   Duplicate definition for ADD-SPECIALIZATION found in one file.
;   See also:
;     The ANSI Standard, Section 3.2.2.3
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {10016C8003}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "polymorphic-functions" "specializing">

```

*polymorphic-functions/swank* fails to build because of a failure in  _polymorphic-functions_.

[Full log here](http://report.quicklisp.org/2022-09-26/failure-report/polymorphic-functions.html)

**Comment by digikar99** [comment]
I have fixed the issue in https://github.com/digikar99/polymorphic-functions/commit/8f6fbb578ea2547876fa95ee49baf5091efa9bcb and moved the tag v0.2.4 (latest) to https://github.com/digikar99/polymorphic-functions/commit/8f6fbb578ea2547876fa95ee49baf5091efa9bcb from the previous commit https://github.com/digikar99/polymorphic-functions/commit/537d9e7dfffddd0b0d779b4ea01af4cab4583de3

**Comment by digikar99** [comment]
I'm closing this issue as it is no longer relevant. (It's 2024 now!)
